/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#88d3d3",
        "primary-fixed": "#a4f0ef",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d9e5e2",
        "surface-container": "#efeded",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3e4947",
        "on-background": "#1b1c1c",
        "outline": "#6f7979",
        "tertiary-fixed-dim": "#bdc9c6",
        "surface-dim": "#dbdad9",
        "background": "#fbf9f8",
        "surface-container-low": "#f5f3f3",
        "tertiary-container": "#697472",
        "on-primary-fixed-variant": "#004f50",
        "on-error-container": "#93000a",
        "outline-variant": "#bec9c8",
        "secondary-container": "#c496ff",
        "tertiary": "#505c5a",
        "surface-container-high": "#e9e8e7",
        "inverse-primary": "#88d3d3",
        "on-tertiary-fixed": "#131e1c",
        "on-surface-variant": "#3f4948",
        "surface-container-highest": "#e4e2e2",
        "surface-tint": "#0e6969",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#dafffe",
        "secondary-fixed": "#eedcff",
        "secondary-fixed-dim": "#d9b9ff",
        "secondary": "#7348ab",
        "on-tertiary-container": "#eefaf7",
        "surface-bright": "#fbf9f8",
        "primary": "#016464",
        "on-primary-fixed": "#002020",
        "surface-variant": "#e4e2e2",
        "inverse-surface": "#303031",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed": "#290054",
        "inverse-on-surface": "#f2f0f0",
        "error": "#ba1a1a",
        "primary-container": "#2d7d7d",
        "surface": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#5a2f91",
        "on-secondary-container": "#532689"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Be Vietnam Pro", "sans-serif"]
      }
    },
  },
  plugins: [],
}
